// Code generated by entc, DO NOT EDIT.

package statusroom

const (
	// Label holds the string label denoting the statusroom type in the database.
	Label = "status_room"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatusName holds the string denoting the status_name field in the database.
	FieldStatusName = "status_name"

	// EdgeDatarooms holds the string denoting the datarooms edge name in mutations.
	EdgeDatarooms = "datarooms"

	// Table holds the table name of the statusroom in the database.
	Table = "status_rooms"
	// DataroomsTable is the table the holds the datarooms relation/edge.
	DataroomsTable = "data_rooms"
	// DataroomsInverseTable is the table name for the DataRoom entity.
	// It exists in this package in order to avoid circular dependency with the "dataroom" package.
	DataroomsInverseTable = "data_rooms"
	// DataroomsColumn is the table column denoting the datarooms relation/edge.
	DataroomsColumn = "statusroom_id"
)

// Columns holds all SQL columns for statusroom fields.
var Columns = []string{
	FieldID,
	FieldStatusName,
}

var (
	// StatusNameValidator is a validator for the "status_name" field. It is called by the builders before save.
	StatusNameValidator func(string) error
)
