// Code generated by entc, DO NOT EDIT.

package counterstaff

const (
	// Label holds the string label denoting the counterstaff type in the database.
	Label = "counter_staff"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"

	// EdgeCheckins holds the string denoting the checkins edge name in mutations.
	EdgeCheckins = "checkins"
	// EdgeCheckouts holds the string denoting the checkouts edge name in mutations.
	EdgeCheckouts = "checkouts"
	// EdgeDetails holds the string denoting the details edge name in mutations.
	EdgeDetails = "details"

	// Table holds the table name of the counterstaff in the database.
	Table = "counter_staffs"
	// CheckinsTable is the table the holds the checkins relation/edge.
	CheckinsTable = "check_ins"
	// CheckinsInverseTable is the table name for the CheckIn entity.
	// It exists in this package in order to avoid circular dependency with the "checkin" package.
	CheckinsInverseTable = "check_ins"
	// CheckinsColumn is the table column denoting the checkins relation/edge.
	CheckinsColumn = "staff_id"
	// CheckoutsTable is the table the holds the checkouts relation/edge.
	CheckoutsTable = "checkouts"
	// CheckoutsInverseTable is the table name for the Checkout entity.
	// It exists in this package in order to avoid circular dependency with the "checkout" package.
	CheckoutsInverseTable = "checkouts"
	// CheckoutsColumn is the table column denoting the checkouts relation/edge.
	CheckoutsColumn = "staff_id"
	// DetailsTable is the table the holds the details relation/edge.
	DetailsTable = "furniture_details"
	// DetailsInverseTable is the table name for the FurnitureDetail entity.
	// It exists in this package in order to avoid circular dependency with the "furnituredetail" package.
	DetailsInverseTable = "furniture_details"
	// DetailsColumn is the table column denoting the details relation/edge.
	DetailsColumn = "staff_id"
)

// Columns holds all SQL columns for counterstaff fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEmail,
	FieldPassword,
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
)
