// Code generated by entc, DO NOT EDIT.

package fixroom

const (
	// Label holds the string label denoting the fixroom type in the database.
	Label = "fix_room"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFixDetail holds the string denoting the fix_detail field in the database.
	FieldFixDetail = "fix_detail"

	// EdgeCustomer holds the string denoting the customer edge name in mutations.
	EdgeCustomer = "customer"
	// EdgeFurnitureDetail holds the string denoting the furnituredetail edge name in mutations.
	EdgeFurnitureDetail = "furnitureDetail"
	// EdgeRoom holds the string denoting the room edge name in mutations.
	EdgeRoom = "room"

	// Table holds the table name of the fixroom in the database.
	Table = "fix_rooms"
	// CustomerTable is the table the holds the customer relation/edge.
	CustomerTable = "fix_rooms"
	// CustomerInverseTable is the table name for the Customer entity.
	// It exists in this package in order to avoid circular dependency with the "customer" package.
	CustomerInverseTable = "customers"
	// CustomerColumn is the table column denoting the customer relation/edge.
	CustomerColumn = "customer_id"
	// FurnitureDetailTable is the table the holds the furnitureDetail relation/edge.
	FurnitureDetailTable = "fix_rooms"
	// FurnitureDetailInverseTable is the table name for the FurnitureDetail entity.
	// It exists in this package in order to avoid circular dependency with the "furnituredetail" package.
	FurnitureDetailInverseTable = "furniture_details"
	// FurnitureDetailColumn is the table column denoting the furnitureDetail relation/edge.
	FurnitureDetailColumn = "object_id"
	// RoomTable is the table the holds the room relation/edge.
	RoomTable = "fix_rooms"
	// RoomInverseTable is the table name for the DataRoom entity.
	// It exists in this package in order to avoid circular dependency with the "dataroom" package.
	RoomInverseTable = "data_rooms"
	// RoomColumn is the table column denoting the room relation/edge.
	RoomColumn = "room_id"
)

// Columns holds all SQL columns for fixroom fields.
var Columns = []string{
	FieldID,
	FieldFixDetail,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the FixRoom type.
var ForeignKeys = []string{
	"customer_id",
	"room_id",
	"object_id",
}
