// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team18/app/ent/dataroom"
	"github.com/team18/app/ent/predicate"
)

// DataRoomDelete is the builder for deleting a DataRoom entity.
type DataRoomDelete struct {
	config
	hooks      []Hook
	mutation   *DataRoomMutation
	predicates []predicate.DataRoom
}

// Where adds a new predicate to the delete builder.
func (drd *DataRoomDelete) Where(ps ...predicate.DataRoom) *DataRoomDelete {
	drd.predicates = append(drd.predicates, ps...)
	return drd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (drd *DataRoomDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(drd.hooks) == 0 {
		affected, err = drd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DataRoomMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			drd.mutation = mutation
			affected, err = drd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(drd.hooks) - 1; i >= 0; i-- {
			mut = drd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, drd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (drd *DataRoomDelete) ExecX(ctx context.Context) int {
	n, err := drd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (drd *DataRoomDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: dataroom.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: dataroom.FieldID,
			},
		},
	}
	if ps := drd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, drd.driver, _spec)
}

// DataRoomDeleteOne is the builder for deleting a single DataRoom entity.
type DataRoomDeleteOne struct {
	drd *DataRoomDelete
}

// Exec executes the deletion query.
func (drdo *DataRoomDeleteOne) Exec(ctx context.Context) error {
	n, err := drdo.drd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dataroom.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (drdo *DataRoomDeleteOne) ExecX(ctx context.Context) {
	drdo.drd.ExecX(ctx)
}
