// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team18/app/ent/predicate"
	"github.com/team18/app/ent/statusreserve"
)

// StatusReserveDelete is the builder for deleting a StatusReserve entity.
type StatusReserveDelete struct {
	config
	hooks      []Hook
	mutation   *StatusReserveMutation
	predicates []predicate.StatusReserve
}

// Where adds a new predicate to the delete builder.
func (srd *StatusReserveDelete) Where(ps ...predicate.StatusReserve) *StatusReserveDelete {
	srd.predicates = append(srd.predicates, ps...)
	return srd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (srd *StatusReserveDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(srd.hooks) == 0 {
		affected, err = srd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StatusReserveMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			srd.mutation = mutation
			affected, err = srd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(srd.hooks) - 1; i >= 0; i-- {
			mut = srd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, srd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (srd *StatusReserveDelete) ExecX(ctx context.Context) int {
	n, err := srd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (srd *StatusReserveDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: statusreserve.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: statusreserve.FieldID,
			},
		},
	}
	if ps := srd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, srd.driver, _spec)
}

// StatusReserveDeleteOne is the builder for deleting a single StatusReserve entity.
type StatusReserveDeleteOne struct {
	srd *StatusReserveDelete
}

// Exec executes the deletion query.
func (srdo *StatusReserveDeleteOne) Exec(ctx context.Context) error {
	n, err := srdo.srd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{statusreserve.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (srdo *StatusReserveDeleteOne) ExecX(ctx context.Context) {
	srdo.srd.ExecX(ctx)
}
