// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team18/app/ent/predicate"
	"github.com/team18/app/ent/reserveroom"
	"github.com/team18/app/ent/statusreserve"
)

// StatusReserveUpdate is the builder for updating StatusReserve entities.
type StatusReserveUpdate struct {
	config
	hooks      []Hook
	mutation   *StatusReserveMutation
	predicates []predicate.StatusReserve
}

// Where adds a new predicate for the builder.
func (sru *StatusReserveUpdate) Where(ps ...predicate.StatusReserve) *StatusReserveUpdate {
	sru.predicates = append(sru.predicates, ps...)
	return sru
}

// SetStatusName sets the status_name field.
func (sru *StatusReserveUpdate) SetStatusName(s string) *StatusReserveUpdate {
	sru.mutation.SetStatusName(s)
	return sru
}

// AddReserfIDs adds the reserves edge to ReserveRoom by ids.
func (sru *StatusReserveUpdate) AddReserfIDs(ids ...int) *StatusReserveUpdate {
	sru.mutation.AddReserfIDs(ids...)
	return sru
}

// AddReserves adds the reserves edges to ReserveRoom.
func (sru *StatusReserveUpdate) AddReserves(r ...*ReserveRoom) *StatusReserveUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return sru.AddReserfIDs(ids...)
}

// Mutation returns the StatusReserveMutation object of the builder.
func (sru *StatusReserveUpdate) Mutation() *StatusReserveMutation {
	return sru.mutation
}

// RemoveReserfIDs removes the reserves edge to ReserveRoom by ids.
func (sru *StatusReserveUpdate) RemoveReserfIDs(ids ...int) *StatusReserveUpdate {
	sru.mutation.RemoveReserfIDs(ids...)
	return sru
}

// RemoveReserves removes reserves edges to ReserveRoom.
func (sru *StatusReserveUpdate) RemoveReserves(r ...*ReserveRoom) *StatusReserveUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return sru.RemoveReserfIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (sru *StatusReserveUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := sru.mutation.StatusName(); ok {
		if err := statusreserve.StatusNameValidator(v); err != nil {
			return 0, &ValidationError{Name: "status_name", err: fmt.Errorf("ent: validator failed for field \"status_name\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(sru.hooks) == 0 {
		affected, err = sru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StatusReserveMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sru.mutation = mutation
			affected, err = sru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sru.hooks) - 1; i >= 0; i-- {
			mut = sru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (sru *StatusReserveUpdate) SaveX(ctx context.Context) int {
	affected, err := sru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (sru *StatusReserveUpdate) Exec(ctx context.Context) error {
	_, err := sru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sru *StatusReserveUpdate) ExecX(ctx context.Context) {
	if err := sru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (sru *StatusReserveUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   statusreserve.Table,
			Columns: statusreserve.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: statusreserve.FieldID,
			},
		},
	}
	if ps := sru.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sru.mutation.StatusName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: statusreserve.FieldStatusName,
		})
	}
	if nodes := sru.mutation.RemovedReservesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statusreserve.ReservesTable,
			Columns: []string{statusreserve.ReservesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: reserveroom.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sru.mutation.ReservesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statusreserve.ReservesTable,
			Columns: []string{statusreserve.ReservesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: reserveroom.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, sru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statusreserve.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// StatusReserveUpdateOne is the builder for updating a single StatusReserve entity.
type StatusReserveUpdateOne struct {
	config
	hooks    []Hook
	mutation *StatusReserveMutation
}

// SetStatusName sets the status_name field.
func (sruo *StatusReserveUpdateOne) SetStatusName(s string) *StatusReserveUpdateOne {
	sruo.mutation.SetStatusName(s)
	return sruo
}

// AddReserfIDs adds the reserves edge to ReserveRoom by ids.
func (sruo *StatusReserveUpdateOne) AddReserfIDs(ids ...int) *StatusReserveUpdateOne {
	sruo.mutation.AddReserfIDs(ids...)
	return sruo
}

// AddReserves adds the reserves edges to ReserveRoom.
func (sruo *StatusReserveUpdateOne) AddReserves(r ...*ReserveRoom) *StatusReserveUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return sruo.AddReserfIDs(ids...)
}

// Mutation returns the StatusReserveMutation object of the builder.
func (sruo *StatusReserveUpdateOne) Mutation() *StatusReserveMutation {
	return sruo.mutation
}

// RemoveReserfIDs removes the reserves edge to ReserveRoom by ids.
func (sruo *StatusReserveUpdateOne) RemoveReserfIDs(ids ...int) *StatusReserveUpdateOne {
	sruo.mutation.RemoveReserfIDs(ids...)
	return sruo
}

// RemoveReserves removes reserves edges to ReserveRoom.
func (sruo *StatusReserveUpdateOne) RemoveReserves(r ...*ReserveRoom) *StatusReserveUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return sruo.RemoveReserfIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (sruo *StatusReserveUpdateOne) Save(ctx context.Context) (*StatusReserve, error) {
	if v, ok := sruo.mutation.StatusName(); ok {
		if err := statusreserve.StatusNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "status_name", err: fmt.Errorf("ent: validator failed for field \"status_name\": %w", err)}
		}
	}

	var (
		err  error
		node *StatusReserve
	)
	if len(sruo.hooks) == 0 {
		node, err = sruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StatusReserveMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sruo.mutation = mutation
			node, err = sruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sruo.hooks) - 1; i >= 0; i-- {
			mut = sruo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sruo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (sruo *StatusReserveUpdateOne) SaveX(ctx context.Context) *StatusReserve {
	sr, err := sruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return sr
}

// Exec executes the query on the entity.
func (sruo *StatusReserveUpdateOne) Exec(ctx context.Context) error {
	_, err := sruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sruo *StatusReserveUpdateOne) ExecX(ctx context.Context) {
	if err := sruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (sruo *StatusReserveUpdateOne) sqlSave(ctx context.Context) (sr *StatusReserve, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   statusreserve.Table,
			Columns: statusreserve.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: statusreserve.FieldID,
			},
		},
	}
	id, ok := sruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing StatusReserve.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := sruo.mutation.StatusName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: statusreserve.FieldStatusName,
		})
	}
	if nodes := sruo.mutation.RemovedReservesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statusreserve.ReservesTable,
			Columns: []string{statusreserve.ReservesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: reserveroom.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sruo.mutation.ReservesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statusreserve.ReservesTable,
			Columns: []string{statusreserve.ReservesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: reserveroom.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	sr = &StatusReserve{config: sruo.config}
	_spec.Assign = sr.assignValues
	_spec.ScanValues = sr.scanValues()
	if err = sqlgraph.UpdateNode(ctx, sruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statusreserve.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return sr, nil
}
