/* tslint:disable */
/* eslint-disable */
/**
 * SUT SE Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntFurnitureTypeEdges,
    EntFurnitureTypeEdgesFromJSON,
    EntFurnitureTypeEdgesFromJSONTyped,
    EntFurnitureTypeEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntFurnitureType
 */
export interface EntFurnitureType {
    /**
     * 
     * @type {EntFurnitureTypeEdges}
     * @memberof EntFurnitureType
     */
    edges?: EntFurnitureTypeEdges;
    /**
     * FurnitureType holds the value of the "furniture_type" field.
     * @type {string}
     * @memberof EntFurnitureType
     */
    furnitureType?: string;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntFurnitureType
     */
    id?: number;
}

export function EntFurnitureTypeFromJSON(json: any): EntFurnitureType {
    return EntFurnitureTypeFromJSONTyped(json, false);
}

export function EntFurnitureTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntFurnitureType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntFurnitureTypeEdgesFromJSON(json['edges']),
        'furnitureType': !exists(json, 'furniture_type') ? undefined : json['furniture_type'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntFurnitureTypeToJSON(value?: EntFurnitureType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntFurnitureTypeEdgesToJSON(value.edges),
        'furniture_type': value.furnitureType,
        'id': value.id,
    };
}


