/* tslint:disable */
/* eslint-disable */
/**
 * SUT SE Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCheckIn,
    EntCheckInFromJSON,
    EntCheckInFromJSONTyped,
    EntCheckInToJSON,
    EntCheckout,
    EntCheckoutFromJSON,
    EntCheckoutFromJSONTyped,
    EntCheckoutToJSON,
    EntFurnitureDetail,
    EntFurnitureDetailFromJSON,
    EntFurnitureDetailFromJSONTyped,
    EntFurnitureDetailToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntCounterStaffEdges
 */
export interface EntCounterStaffEdges {
    /**
     * Checkins holds the value of the checkins edge.
     * @type {Array<EntCheckIn>}
     * @memberof EntCounterStaffEdges
     */
    checkins?: Array<EntCheckIn>;
    /**
     * Checkouts holds the value of the checkouts edge.
     * @type {Array<EntCheckout>}
     * @memberof EntCounterStaffEdges
     */
    checkouts?: Array<EntCheckout>;
    /**
     * Details holds the value of the details edge.
     * @type {Array<EntFurnitureDetail>}
     * @memberof EntCounterStaffEdges
     */
    details?: Array<EntFurnitureDetail>;
}

export function EntCounterStaffEdgesFromJSON(json: any): EntCounterStaffEdges {
    return EntCounterStaffEdgesFromJSONTyped(json, false);
}

export function EntCounterStaffEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntCounterStaffEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'checkins': !exists(json, 'checkins') ? undefined : ((json['checkins'] as Array<any>).map(EntCheckInFromJSON)),
        'checkouts': !exists(json, 'checkouts') ? undefined : ((json['checkouts'] as Array<any>).map(EntCheckoutFromJSON)),
        'details': !exists(json, 'details') ? undefined : ((json['details'] as Array<any>).map(EntFurnitureDetailFromJSON)),
    };
}

export function EntCounterStaffEdgesToJSON(value?: EntCounterStaffEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'checkins': value.checkins === undefined ? undefined : ((value.checkins as Array<any>).map(EntCheckInToJSON)),
        'checkouts': value.checkouts === undefined ? undefined : ((value.checkouts as Array<any>).map(EntCheckoutToJSON)),
        'details': value.details === undefined ? undefined : ((value.details as Array<any>).map(EntFurnitureDetailToJSON)),
    };
}


