/* tslint:disable */
/* eslint-disable */
/**
 * SUT SE Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCheckIn,
    EntCheckInFromJSON,
    EntCheckInFromJSONTyped,
    EntCheckInToJSON,
    EntFixRoom,
    EntFixRoomFromJSON,
    EntFixRoomFromJSONTyped,
    EntFixRoomToJSON,
    EntFurnitureDetail,
    EntFurnitureDetailFromJSON,
    EntFurnitureDetailFromJSONTyped,
    EntFurnitureDetailToJSON,
    EntPromotion,
    EntPromotionFromJSON,
    EntPromotionFromJSONTyped,
    EntPromotionToJSON,
    EntReserveRoom,
    EntReserveRoomFromJSON,
    EntReserveRoomFromJSONTyped,
    EntReserveRoomToJSON,
    EntStatusRoom,
    EntStatusRoomFromJSON,
    EntStatusRoomFromJSONTyped,
    EntStatusRoomToJSON,
    EntTypeRoom,
    EntTypeRoomFromJSON,
    EntTypeRoomFromJSONTyped,
    EntTypeRoomToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDataRoomEdges
 */
export interface EntDataRoomEdges {
    /**
     * Checkins holds the value of the checkins edge.
     * @type {Array<EntCheckIn>}
     * @memberof EntDataRoomEdges
     */
    checkins?: Array<EntCheckIn>;
    /**
     * Details holds the value of the details edge.
     * @type {Array<EntFurnitureDetail>}
     * @memberof EntDataRoomEdges
     */
    details?: Array<EntFurnitureDetail>;
    /**
     * Fixs holds the value of the fixs edge.
     * @type {Array<EntFixRoom>}
     * @memberof EntDataRoomEdges
     */
    fixs?: Array<EntFixRoom>;
    /**
     * 
     * @type {EntPromotion}
     * @memberof EntDataRoomEdges
     */
    promotion?: EntPromotion;
    /**
     * Reserves holds the value of the reserves edge.
     * @type {Array<EntReserveRoom>}
     * @memberof EntDataRoomEdges
     */
    reserves?: Array<EntReserveRoom>;
    /**
     * 
     * @type {EntStatusRoom}
     * @memberof EntDataRoomEdges
     */
    statusroom?: EntStatusRoom;
    /**
     * 
     * @type {EntTypeRoom}
     * @memberof EntDataRoomEdges
     */
    typeroom?: EntTypeRoom;
}

export function EntDataRoomEdgesFromJSON(json: any): EntDataRoomEdges {
    return EntDataRoomEdgesFromJSONTyped(json, false);
}

export function EntDataRoomEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDataRoomEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'checkins': !exists(json, 'checkins') ? undefined : ((json['checkins'] as Array<any>).map(EntCheckInFromJSON)),
        'details': !exists(json, 'details') ? undefined : ((json['details'] as Array<any>).map(EntFurnitureDetailFromJSON)),
        'fixs': !exists(json, 'fixs') ? undefined : ((json['fixs'] as Array<any>).map(EntFixRoomFromJSON)),
        'promotion': !exists(json, 'promotion') ? undefined : EntPromotionFromJSON(json['promotion']),
        'reserves': !exists(json, 'reserves') ? undefined : ((json['reserves'] as Array<any>).map(EntReserveRoomFromJSON)),
        'statusroom': !exists(json, 'statusroom') ? undefined : EntStatusRoomFromJSON(json['statusroom']),
        'typeroom': !exists(json, 'typeroom') ? undefined : EntTypeRoomFromJSON(json['typeroom']),
    };
}

export function EntDataRoomEdgesToJSON(value?: EntDataRoomEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'checkins': value.checkins === undefined ? undefined : ((value.checkins as Array<any>).map(EntCheckInToJSON)),
        'details': value.details === undefined ? undefined : ((value.details as Array<any>).map(EntFurnitureDetailToJSON)),
        'fixs': value.fixs === undefined ? undefined : ((value.fixs as Array<any>).map(EntFixRoomToJSON)),
        'promotion': EntPromotionToJSON(value.promotion),
        'reserves': value.reserves === undefined ? undefined : ((value.reserves as Array<any>).map(EntReserveRoomToJSON)),
        'statusroom': EntStatusRoomToJSON(value.statusroom),
        'typeroom': EntTypeRoomToJSON(value.typeroom),
    };
}


