/* tslint:disable */
/* eslint-disable */
/**
 * SUT SE Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntFurnitureDetail,
    EntFurnitureDetailFromJSON,
    EntFurnitureDetailFromJSONTyped,
    EntFurnitureDetailToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntFurnitureEdges
 */
export interface EntFurnitureEdges {
    /**
     * Details holds the value of the details edge.
     * @type {Array<EntFurnitureDetail>}
     * @memberof EntFurnitureEdges
     */
    details?: Array<EntFurnitureDetail>;
}

export function EntFurnitureEdgesFromJSON(json: any): EntFurnitureEdges {
    return EntFurnitureEdgesFromJSONTyped(json, false);
}

export function EntFurnitureEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntFurnitureEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'details': !exists(json, 'details') ? undefined : ((json['details'] as Array<any>).map(EntFurnitureDetailFromJSON)),
    };
}

export function EntFurnitureEdgesToJSON(value?: EntFurnitureEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'details': value.details === undefined ? undefined : ((value.details as Array<any>).map(EntFurnitureDetailToJSON)),
    };
}


