// Code generated by entc, DO NOT EDIT.

package furniture

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/team18/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// FurnitureName applies equality check predicate on the "furniture_name" field. It's identical to FurnitureNameEQ.
func FurnitureName(v string) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFurnitureName), v))
	})
}

// FurnitureNameEQ applies the EQ predicate on the "furniture_name" field.
func FurnitureNameEQ(v string) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFurnitureName), v))
	})
}

// FurnitureNameNEQ applies the NEQ predicate on the "furniture_name" field.
func FurnitureNameNEQ(v string) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldFurnitureName), v))
	})
}

// FurnitureNameIn applies the In predicate on the "furniture_name" field.
func FurnitureNameIn(vs ...string) predicate.Furniture {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Furniture(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldFurnitureName), v...))
	})
}

// FurnitureNameNotIn applies the NotIn predicate on the "furniture_name" field.
func FurnitureNameNotIn(vs ...string) predicate.Furniture {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Furniture(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldFurnitureName), v...))
	})
}

// FurnitureNameGT applies the GT predicate on the "furniture_name" field.
func FurnitureNameGT(v string) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldFurnitureName), v))
	})
}

// FurnitureNameGTE applies the GTE predicate on the "furniture_name" field.
func FurnitureNameGTE(v string) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldFurnitureName), v))
	})
}

// FurnitureNameLT applies the LT predicate on the "furniture_name" field.
func FurnitureNameLT(v string) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldFurnitureName), v))
	})
}

// FurnitureNameLTE applies the LTE predicate on the "furniture_name" field.
func FurnitureNameLTE(v string) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldFurnitureName), v))
	})
}

// FurnitureNameContains applies the Contains predicate on the "furniture_name" field.
func FurnitureNameContains(v string) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldFurnitureName), v))
	})
}

// FurnitureNameHasPrefix applies the HasPrefix predicate on the "furniture_name" field.
func FurnitureNameHasPrefix(v string) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldFurnitureName), v))
	})
}

// FurnitureNameHasSuffix applies the HasSuffix predicate on the "furniture_name" field.
func FurnitureNameHasSuffix(v string) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldFurnitureName), v))
	})
}

// FurnitureNameEqualFold applies the EqualFold predicate on the "furniture_name" field.
func FurnitureNameEqualFold(v string) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldFurnitureName), v))
	})
}

// FurnitureNameContainsFold applies the ContainsFold predicate on the "furniture_name" field.
func FurnitureNameContainsFold(v string) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldFurnitureName), v))
	})
}

// HasDetails applies the HasEdge predicate on the "details" edge.
func HasDetails() predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DetailsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DetailsTable, DetailsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDetailsWith applies the HasEdge predicate on the "details" edge with a given conditions (other predicates).
func HasDetailsWith(preds ...predicate.FurnitureDetail) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DetailsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DetailsTable, DetailsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Furniture) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Furniture) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Furniture) predicate.Furniture {
	return predicate.Furniture(func(s *sql.Selector) {
		p(s.Not())
	})
}
